    services:
    - type: web
      name: news-rewriter-api
      env: python
      plan: free
      buildCommand: pip install -r requirements.txt
      startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
      envVars:
        - key: API_KEY
          sync: false
        - key: GITHUB_TOKEN
          sync: false
        - key: WORDPRESS_API_TOKEN
          sync: false
        - key: WORDPRESS_APP_PASSWORD
          sync: false
        - key: WORDPRESS_SITE_URL
          value: https://therimonline.com
        - key: ACCESS_PASSWORD
          sync: false
      healthCheckPath: /
